{% set name = "witty" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/witty-{{ version }}.tar.gz
  sha256: 8ee71ba3321c77b64fd9d3a33c2f9ed2424cd7798ee22a4519687c2a88e0f108

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - cython >=3.0,<3.2
    - setuptools
    - nanobind >=0.2.8
    - {{ compiler('cxx') }}

test:
  imports:
    - witty
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/funkelab/witty
  summary: Well-in-Time Compiler for Cython Modules
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tlambert03
    - funkey
